Toniof cube type
dcs4cop/xcube pull request #339
Opened 2020-09-29 12:15 UTC by TonioF

Introduces new notation to denote types that have been derived from dataset and includes a new type ( dataset[cube] ) and a new DataDescriptor ( CubeDescriptor ).

2020-09-29 15:05 UTC, forman requested changes
Besides my comments below, this implementation is incomplete. It does not reflect the semantics of the new `type_id` when passed to the following methods:

* [xcube.core.store.accessor.get_data_accessor_predicate()](https://github.com/dcs4cop/xcube/blob/master/xcube/core/store/accessor.py#L106)
* [xcube.core.store.store.DataStore.get_data_ids()](https://github.com/dcs4cop/xcube/blob/master/xcube/core/store/store.py#L104)
* [xcube.core.store.store.DataStore.search_data()](https://github.com/dcs4cop/xcube/blob/master/xcube/core/store/store.py#L104)
* [xcube.core.store.store.DataStore.get_data_opener_ids()](https://github.com/dcs4cop/xcube/blob/master/xcube/core/store/store.py#L104)
* [xcube.core.store.store.DataStore.get_data_writer_ids()](https://github.com/dcs4cop/xcube/blob/master/xcube/core/store/store.py#L261)

For the purpose of comparing two type_ids, I suggest we introduce a new class `TypeId`:

```python
class TypeId:

    def __init__(self, type_id: str):
        name, flags = self.parse_type_id(type_id)
        self._name: str = name
        self._flags: set = flags
 
    @property
    def name(self) -> str:
        return self._name

    @property
    def flags(self) -> Set[str]:
        return self._name

    def __eq__(self, other) -> bool:
        ...

    def __hash__(self) -> int:
        return hash(self.name) + 16 * hash(self.flags)

    @classmethod
    def normalize(cls, type_id: Union[str, "TypeId"]) -> TypeId:
        if instanceof(type_id, TypeId):
            return type_id
        if instanceof(type_id, str):
            return cls.parse(type_id)
        raise TypeError('type_id must be of type "str" or "TypeId"')

    @classmethod
    def parse(cls, type_id: str) -> TypeId:
         ..

```

And in the methods mentioned above, we allow `type_id` to be of either type `str` or `TypeId`: `Union[str, TypeId]`. To normalize, we call `TypeId.normalize(type_id)`.

2020-09-29 15:59 UTC, pont-us approved these changes
Approving since I have nothing to add to @forman 's review.

2020-09-29 16:00 UTC, TonioF commented on test/core/store/test_descriptor.py
> +        descriptor_dict = dict(data_id='xyz', type_id='dataset[fegd]')
Yes. This test only tests whether it is a dataset. It may hold any potential additional flags.

2020-09-29 16:03 UTC, TonioF commented on xcube/core/store/descriptor.py
> +            raise ValueError('Type ID must start with dataset')
No. It must start with dataset and then hold the flag multilevel . (This might change when we agree to use the class TypeId as proposed above.)

2020-09-29 16:05 UTC, TonioF commented on xcube/core/store/descriptor.py
> +            raise ValueError("Type ID must contain 'multilevel'")
We are in the class MultiLevelDatasetDescriptor. This one definitely expects the flag multilevel to be set.

2020-10-08 13:25 UTC, TonioF commented
I have completely overhauled the pr. Now, the TypeId - class as proposed in @forman 's comment is used, and it is considered in the implementations of the stores.
MultilevelDataset is not considered a type of Dataset anymore, as they are two different classes and adhere to different interfaces. We now only have a flag cube to indicate that every cube is also a dataset.
I have further introduced a type id ANY_TYPE which corresponds to the asterisk which is used by some accessors to indicate that they work with any kind of data.

2020-10-08 14:35 UTC, pont-us approved these changes

2020-10-28 16:34 UTC, forman requested changes
Very good, thanks for this!

We still need to discuss about how to deal with `MultiLevelDataset` which actually _is a_ `Dataset`, but not yet in Python terms. See my comments in `TypeId`.

2020-10-28 16:34 UTC, forman commented on test/core/store/test_typeid.py
> +class TypeIdTest(unittest.TestCase):
In `TypeIdTest` test methods, please use names and flags that apply to our context, so we (and others) can better grasp the intention of `TypeId`.

2020-10-28 16:34 UTC, forman commented on xcube/core/store/descriptor.py
> +            raise ValueError('TypeId must be "dataset" type id')
```suggestion
            raise ValueError('type_id must be compatible with "dataset"')
```

Note that value errors are used to signal developer errors, hence it should include the name of the actual variable that includes the invalid value (`type_id` here).

2020-10-28 16:34 UTC, forman commented on xcube/core/store/descriptor.py
> +            raise ValueError('TypeId must be "mldataset" type id')
Same as above.

2020-10-28 16:34 UTC, forman commented on xcube/core/store/descriptor.py
> +            raise ValueError('TypeId must be "geodataframe" type id')
Same as above.

2020-10-28 16:34 UTC, forman commented on xcube/core/store/typeid.py
> +TYPE_ID_MULTI_LEVEL_DATASET = TypeId('mldataset')
Actually, this is the correct definition:

```suggestion
TYPE_ID_MULTI_LEVEL_DATASET = TypeId('dataset', flags={'multilevel'})
```

However, a `MultiLevelDataset` is not yet an instance  of `xarray.Dataset` but that should be possible later.

2020-10-28 16:34 UTC, forman commented on xcube/core/store/typeid.py
> +    elif isinstance(data, MultiLevelDataset):
See comment above.

2020-10-28 16:34 UTC, forman commented on xcube/core/store/typeid.py
> +    """
Missing description of paramerters to `__init__()`.

2020-10-28 16:37 UTC, forman commented on xcube/core/store/descriptor.py
> +            raise ValueError("Type ID must contain 'multilevel'")
See my new comments. MLDataset _is a_ dataset.

2020-10-28 16:37 UTC, forman commented on xcube/core/store/descriptor.py
> +            raise ValueError('Type ID must start with dataset')
Still error message are not correctly formatted, see my new comments.

2020-10-29 14:33 UTC, TonioF commented
@forman , I have applied most of your change requests.
I do not feel too well with treating multileveldatasets as a sub-type of datasets already. E.g., if I have a DataOpener for Datasets, I would expect that I can open all types of datasets with them. I would use a MultilevelDataOpener if I want to ensure that what I open meets the criteria of a multileveldataset. This expectation would not be met if we already make MultilevelDatasets sub-types of datasets.
Having stated my concerns, do you still want me to make this change to the pr?

2020-10-29 14:49 UTC, pont-us approved these changes

2020-10-29 15:40 UTC, merged