Toniof xcube397 threadsafe progress monitors
dcs4cop/xcube pull request #398
Opened 2021-01-19 09:19 UTC by TonioF

There is no central progress state stack anymore. Instead, every progress state knows its parent state. A state may be the parent of more than one other state. To determine the parent, the traceback is considered. This works for progresses happening within the same thread, including tasks started with asyncio. Progresses started from another thread will have no parent (unless there is already another progress from the same thread).

Related issue: #397 

Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
~~*New/modified features documented in `docs/source/*~~
* [ ] Changes documented in `docs/CHANGES.md`
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage remains or increases (target 100%)
* [ ] Associated issues closed after merge

2021-01-19 09:30 UTC, TonioF commented
Issues with this approach:
- It creates "rogue" progress states. Progress Observers need to make sure what progress state stack they are dealing with.

2021-02-02 13:23 UTC, forman reviewed
Sorry, I cannot review this without an explanation why and how this works.

2021-02-02 13:23 UTC, forman commented on test/util/test_progress.py
> +class AsyncProgressTest(unittest.TestCase):
Please add a docstring about purpose and bahaviour of this class

2021-02-02 13:40 UTC, TonioF commented
Added another doc string. That aside, please have a look at the pr description.

2021-02-03 08:29 UTC, forman commented
> have a look at the pr description.

The PR description will be invisible once the PR is accepted. What reamins is the docstring in the code. This will help readers understand our code. I don't want them to read our PR descriptions.

2021-02-03 08:41 UTC, forman requested changes
It just takes me too much time understanding what has been implemented here. Requires a chat.

2021-02-03 08:41 UTC, forman commented on xcube/util/progress.py
> +        return file_part, int(in_file_parts[0]), in_file_parts[1]
That is a lot of magic. Please explain what is done here and why.

2021-02-03 08:41 UTC, forman commented on xcube/util/progress.py
> +        return parent_state
Wow.

2021-02-03 08:41 UTC, forman commented on xcube/util/progress.py
> +            self._stack.append(self)
```suggestion
            self._stack = [self]
```

2021-02-03 08:41 UTC, forman commented on xcube/util/progress.py
> +        if not self._stack:
Not thread-safe.

2021-02-03 08:41 UTC, forman commented on xcube/util/progress.py
> +        if self._parent:
Not thread-safe.

2021-02-03 08:41 UTC, forman commented on xcube/util/progress.py
> +            progress_state.parent.super_work_ahead = 1
Please say, why this is needed. I forgot already.

2021-08-24 07:25 UTC, TonioF commented
Outdated and ultimately deemed a non-favourable solution.

2021-08-24 07:25 UTC, closed without merging