Dzelge xxx gen2 no traceback
dcs4cop/xcube pull request #449
Opened 2021-05-07 10:53 UTC by dzelge

When accepting this PR xcube gen2 will print tracebacks to stderr when raising  CubeGeneratorErrors (#448)

[Description of PR]

Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [ x ] Changes documented in `docs/CHANGES.md`
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage remains or increases (target 100%)
* [ ] Associated issues closed after merge

2021-05-07 12:49 UTC, pont-us approved these changes
Looks fine. Twelve unit tests are failing in CI, but these failures are caused (I'm fairly sure) by the xarray 0.18.0 release yesterday, and are also failing in master.

2021-05-10 07:12 UTC, TonioF approved these changes
Looks good, but I really wish we had a test for this.

2021-05-10 08:03 UTC, forman requested changes
Tiny change only.

2021-05-10 08:03 UTC, forman commented on xcube/cli/gen2.py
> +            print(e.remote_traceback, file=sys.stderr)
```suggestion
            print(e.remote_traceback, **print_kwargs)
```

2021-05-11 07:29 UTC, forman requested changes
Please
- Fix failing AppVeyor build
- Resolve conflicts
- Use checklist

2021-05-26 08:26 UTC, forman approved these changes

2021-05-26 08:27 UTC, merged