improved support of cftime
dcs4cop/xcube pull request #456
Opened 2021-05-18 12:39 UTC by TonioF

A fix to further improve the usability of datasets with time given in a cftime format.
Checklist:

* [x] Add unit tests and/or doctests in docstrings
* ~~[ ] Add docstrings and API docs for any new/modified user-facing classes and functions~~
* ~~[ ] New/modified features documented in `docs/source/*`~~
* ~~[ ] Changes documented in `docs/CHANGES.md`~~
* [ ] AppVeyor and Travis CI passes
* [x] Test coverage remains or increases (target 100%)
* ~~[ ] Associated issues closed after merge~~

2021-05-18 13:20 UTC, forman approved these changes

2021-05-18 13:20 UTC, forman commented on xcube/core/timecoord.py
> +    is_cf_time = type(time.values[0]).__module__.startswith('cftime')
1. `time.values` eagerly loads all time data. 
2. it is not save to use `__module__` names.

```suggestion
    is_cf_time = instanceof(time[0].values.item(), cftime.datetime)
```

2021-05-18 13:20 UTC, forman commented on xcube/core/timecoord.py
> +    data_end = pd.to_datetime(time.values[-1].isoformat()) if is_cf_time else time.values[-1]
Every single `time.values`  call eagerly loads all time data. I explained the implications two weeks or so ago.

```suggestion
    data_start = pd.to_datetime(time[0].values.item().isoformat()) if is_cf_time else time[0].values.item()
    data_end = pd.to_datetime(time[-1].values.item().isoformat()) if is_cf_time else time[-1].values.item()
```

2021-05-18 13:22 UTC, forman requested changes
Avoid eager loading of values.

2021-05-20 14:02 UTC, TonioF commented
I have revised the method (and done a bit of formatting). Thanks for your input.

2021-05-26 08:14 UTC, forman requested changes
Just PEP-8

2021-05-26 08:14 UTC, forman commented on xcube/core/timecoord.py
> +            time_bnds=(['time', 'bnds'], from_time_in_days_since_1970([t1, t2]).reshape(1, 2)))
```suggestion
        dataset = dataset.assign_coords(
            time_bnds=(['time', 'bnds'], from_time_in_days_since_1970([t1, t2]).reshape(1, 2))
        )
```

PEP-8

2021-05-26 08:14 UTC, forman commented on xcube/core/timecoord.py
> +            to_datetime64()
```suggestion
        return pd.to_datetime(time_value, utc=True, unit='d', origin='unix').round(freq='ms') \
            .to_datetime64()
```

PEP-8

2021-05-26 12:51 UTC, merged