Updated Generator Notebooks
dcs4cop/xcube pull request #521
Opened 2021-09-08 15:55 UTC by forman

Updated Generator NBs with respect to #514.

Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [ ] Changes documented in `CHANGES.md`
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

Remember to close associated issues after merge!

2021-09-09 15:57 UTC, TonioF requested changes
Three of these notebooks fail. #1 and #2 do not have an 'edc-service-yml', for #4 get_cube_info fails with DataStoreError: Invalid parameterization detected: 'client_id' is a required property .

2021-09-10 07:41 UTC, AliceBalfanz requested changes
I agree with Tonio, three NBs fail due to missing edc-service.yml (NB nr. 1, 3 and 4.).
@TonioF, you must export your SH client ID and secrets before executing the NBs, then you don't get the error message about client_id.

2021-09-10 09:34 UTC, pont-us requested changes
Like the others, I of course get the same errors from the missing service configuration, but everything works fine when I copy `edc-service-dev-config.yml` in as `edc-service.yml` (and set the environment variables for SH access). I'm not sure what the preferred solution is here -- obviously we can't commit secrets to a public repo, but maybe it would be good to have a prominent notice at the start of the notebook that you need to obtain these credentials, and SH credentials, to make it work.

(Incidentally, I also got a lot of xarray "Failed to open Zarr store with consolidated metadata, falling back to try reading non-consolidated metadata." warnings from both xcube and xcube-sh in Notebook 4, but this is something that needs fixing in the code rather than the notebook, so not a job for this PR.)

2021-09-10 14:18 UTC, forman commented
@AliceBalfanz @TonioF @dzelge @pont-us 

I've added the missing config file `edc-service.yml`. It now expects you to set some env vars:

```yaml
endpoint_url: "${EDC_ENDPOINT_URL}"
client_id: "${EDC_CLIENT_ID}"
client_secret: "${EDC_CLIENT_SECRET}"
```

2021-09-10 15:15 UTC, pont-us requested changes
Looks good! My only requested change is the comment I've suggested adding to the `edc-service.yml` file.

2021-09-10 15:15 UTC, pont-us commented on examples/notebooks/generators/edc-service.yml
> +endpoint_url: "${EDC_ENDPOINT_URL}"
```suggestion
# This file specifies the credentials for the remote generator service used
# in the example notebooks. The settings below read these credentials from
# environment variables. To run the generator examples in the notebooks,
# either set these environment variables before starting the notebook, or
# edit this file to specify the credentials directly.

endpoint_url: "${EDC_ENDPOINT_URL}"
```

2021-09-13 07:47 UTC, AliceBalfanz commented
In 3_remote.ipynb in cell 8:

I used the dev cluster URL and credentials 

```
result = generator.get_cube_info(request)
result
```

```
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
~/Desktop/projects/xcube-dev/xcube/core/gen2/remote/generator.py in _parse_response(self, response, response_type, request_data)
    239         try:
--> 240             return response_type.from_dict(response_data)
    241         except Exception as e:

~/Desktop/projects/xcube-dev/xcube/util/jsonschema.py in from_dict(cls, value)
    608         """Create instance from JSON-serializable dictionary *value*."""
--> 609         return cls.get_schema().from_instance(value)
    610 

~/Desktop/projects/xcube-dev/xcube/util/jsonschema.py in from_instance(self, instance)
    118         # TODO: support anyOf
--> 119         self.validate_instance(instance)
    120         return self._from_validated_instance(instance)

~/Desktop/projects/xcube-dev/xcube/util/jsonschema.py in validate_instance(self, instance)
    103         # date-time format, strict_rfc3339 or rfc3339-validator is required.
--> 104         jsonschema.validate(instance=instance, schema=self.to_dict(),
    105                             format_checker=jsonschema.draft7_format_checker,

~/miniconda3/envs/xcube-dev/lib/python3.9/site-packages/jsonschema/validators.py in validate(instance, schema, cls, *args, **kwargs)
    933     if error is not None:
--> 934         raise error
    935 

ValidationError: 'dataset_descriptor' is a required property

Failed validating 'required' in schema:
    {'additionalProperties': True,
     'properties': {'cost_estimation': {'additionalProperties': False,
                                        'properties': {'available': {'minimum': 0,
                                                                     'type': 'integer'},
                                                       'limit': {'minimum': 0,
                                                                 'type': 'integer'},
                                                       'required': {'minimum': 0,
                                                                    'type': 'integer'}},
                                        'required': ['required'],
                                        'type': 'object'},
                    'dataset_descriptor': {'additionalProperties': False,
                                           'properties': {'attrs': {'additionalProperties': True,
                                                                    'type': 'object'},
                                                          'bbox': {'items': [{'type': 'number'},
                                                                             {'type': 'number'},
                                                                             {'type': 'number'},
                                                                             {'type': 'number'}],
                                                                   'type': 'array'},
                                                          'coords': {'additionalProperties': {'additionalProperties': False,
                                                                                              'properties': {'attrs': {'additionalProperties': True,
                                                                                                                       'type': 'object'},
                                                                                                             'chunks': {'items': {'minimum': 0,
                                                                                                                                  'type': 'integer'},
                                                                                                                        'type': 'array'},
                                                                                                             'dims': {'items': {'minLength': 1,
                                                                                                                                'type': 'string'},
                                                                                                                      'type': 'array'},
                                                                                                             'dtype': {'minLength': 1,
                                                                                                                       'type': 'string'},
                                                                                                             'name': {'minLength': 1,
                                                                                                                      'type': 'string'}},
                                                                                              'required': ['dtype',
                                                                                                           'dims',
                                                                                                           'name'],
                                                                                              'type': 'object'},
                                                                     'type': 'object'},
                                                          'crs': {'minLength': 1,
                                                                  'type': 'string'},
                                                          'data_id': {'minLength': 1,
                                                                      'type': 'string'},
                                                          'data_type': {'minLength': 1,
                                                                        'type': 'string'},
                                                          'data_vars': {'additionalProperties': {'additionalProperties': False,
                                                                                                 'properties': {'attrs': {'additionalProperties': True,
                                                                                                                          'type': 'object'},
                                                                                                                'chunks': {'items': {'minimum': 0,
                                                                                                                                     'type': 'integer'},
                                                                                                                           'type': 'array'},
                                                                                                                'dims': {'items': {'minLength': 1,
                                                                                                                                   'type': 'string'},
                                                                                                                         'type': 'array'},
                                                                                                                'dtype': {'minLength': 1,
                                                                                                                          'type': 'string'},
                                                                                                                'name': {'minLength': 1,
                                                                                                                         'type': 'string'}},
                                                                                                 'required': ['dtype',
          [...]

2021-09-14 06:50 UTC, merged