Toniof 522 provide versions
dcs4cop/xcube pull request #532
Opened 2021-09-16 07:26 UTC by TonioF

Solves #522. I have written the function in a way that it can be re-used by Cate.

Please see whether the output is in all the places where you would expect it.

Checklist:

* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* ~[ ] New/modified features documented in `docs/source/*`~
* [x] Changes documented in `CHANGES.md`
* [x] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

Remember to close associated issues after merge!

2021-09-16 07:54 UTC, forman requested changes
Please rename `dependencies` to `versions`. 

The original idea was to just copy the corresponding function from Cate.
Im not a fan of including any dependency in our responses. This would be another operatioon of the generator API  and the xcube server API.

2021-09-16 07:54 UTC, forman commented on CHANGES.md
> +* Added functions `get_dependencies` and `get_xcube_dependencies` to get
Where are they. Pls provide fully qualified names.

2021-09-16 07:54 UTC, forman commented on xcube/cli/gen2.py
> +                      dependencies=get_xcube_dependencies(),
Please use `versions`

2021-09-16 07:54 UTC, forman commented on xcube/core/gen2/local/generator.py
> +                dependencies = get_xcube_dependencies()
Only include on error

2021-09-16 07:54 UTC, forman commented on xcube/core/gen2/local/generator.py
> +                dependencies=get_xcube_dependencies()
Only include on error

2021-09-16 07:54 UTC, forman commented on xcube/core/gen2/local/generator.py
> +                              dependencies=get_xcube_dependencies())
Only include on error

2021-09-16 07:54 UTC, forman commented on xcube/core/gen2/response.py
> +        self.dependencies = dependencies if dependencies else None
use name `versions`

2021-09-16 07:54 UTC, forman commented on xcube/core/gen2/response.py
> +                dependencies=JsonObjectSchema(additional_properties=True)
use name `versions`

2021-09-16 07:54 UTC, forman commented on xcube/util/dependencies.py
> +def get_xcube_dependencies() -> Dict[str, str]:
* rename function to `get_xcube_versions()`
* rename module to `versions.py`

2021-09-16 08:48 UTC, TonioF commented
> Please rename dependencies to versions.

Okay.

> Im not a fan of including any dependency in our responses. This would be another operatioon of the generator API and the xcube server API.

I changed this, too, but to me this directly contradicts the statement in the issue:

> Should be included in responses of
xcube serve
xcube gen2

2021-09-16 14:23 UTC, forman requested changes
Sorry, still cannot approve it, some minor issues remain.

Maybe we should not recompute the versions dicts on every error, because 
1. it may cost time to load modules that haven't been loaded yet
2. it is not impossible that `get_xcube_version()` raises while we construct an error result for another error

2021-09-16 14:23 UTC, forman commented on xcube/core/gen2/response.py
> +        self.versions = versions if versions else None
```suggestion
        self.versions = dict(versions) if versions else None
```

2021-09-16 14:23 UTC, forman commented on xcube/util/versions.py
> +# Copyright (c) 2019 by the xcube development team and contributors
```suggestion
# Copyright (c) 2021 by the xcube development team and contributors
```

2021-09-16 14:23 UTC, forman commented on test/util/test_dependencies.py
> +import unittest
Please rename `test_dependencies.py` into `test_versions.py`

2021-09-16 14:23 UTC, forman commented on xcube/webapi/service.py
> +                    'versions': get_xcube_versions(),
Maybe not recompute on every error.

2021-09-16 14:23 UTC, forman commented on xcube/core/gen2/remote/generator.py
> +            versions=get_xcube_versions()
Maybe not recompute on every error.

2021-09-17 12:44 UTC, forman approved these changes

2021-09-17 12:44 UTC, merged