Pinning openssl to fix failing unittest on mac
dcs4cop/xcube pull request #578
Opened 2022-01-06 07:00 UTC by AliceBalfanz

[Description of PR]
This PR only adds openssl to the dependencies of xcube, and pins it to the last working version. This should be undone, once https://github.com/conda/conda/issues/11111 is solved. 

No code has changed. 

Checklist:

* [ ] ~~Add unit tests and/or doctests in docstrings~~
* [ ] ~~Add docstrings and API docs for any new/modified user-facing classes and functions~~
* [ ] ~~New/modified features documented in `docs/source/*`~~
* [ ] ~~Changes documented in `CHANGES.md`~~
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

Remember to close associated issues after merge!

2022-01-06 07:53 UTC, AliceBalfanz commented
Docker builds failing due to open PR: https://github.com/dcs4cop/xcube/pull/575

2022-01-06 07:55 UTC, pont-us approved these changes
Looks good!

2022-01-06 08:04 UTC, dzelge approved these changes
We have to check, whether this has implications on the cluster deployments.

2022-01-06 08:06 UTC, dzelge requested changes
Sorry, had to revoke my approval. Unittests fail.

2022-01-06 08:30 UTC, dzelge approved these changes

2022-01-07 15:00 UTC, dzelge requested changes
I would remove the whole line.I don't think that flask-testing and requests-mock is actually beebn used in xcube ubnittests

2022-01-07 15:00 UTC, dzelge commented on .github/workflows/xcube_workflow.yaml
> +          mamba install -c conda-forge  flask-testing requests-mock
```suggestion
```

2022-01-07 16:02 UTC, merged