Fixing tests for accessing data from xcube server via python api
dcs4cop/xcube pull request #592
Opened 2022-01-21 16:01 UTC by AliceBalfanz

This PR only fixes the tests for test_s3buckethandlers.py when serving data the classical way: one dataset per identifyer, as in examples/serve/demo/config.yml . The data access does not work yet for cubes served via DataStores like in the config examples/serve/demo/config-with-stores.yml
Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [ ] Changes documented in `CHANGES.md`
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

Remember to close associated issues after merge!

2022-01-24 08:50 UTC, TonioF reviewed
I tried to review by following the steps to reproduce in the original issue. I could not reproduce it. The tests work your changes, too, though.

2022-01-24 08:53 UTC, AliceBalfanz commented
> I tried to review by following the steps to reproduce in the original issue. I could not reproduce it. The tests work your changes, too, though.

If you delete your .aws (or give it a different name) then you will see the error with the old code :)

2022-01-24 14:45 UTC, TonioF approved these changes
Okay, I could test it now. Works fine!

2022-01-26 12:38 UTC, forman requested changes
Just tiny minor formatting issue :)

2022-01-26 12:38 UTC, forman commented on test/webapi/test_s3buckethandlers.py
> +                       )
```suggestion
                       })
```

2022-01-28 12:24 UTC, merged