Harmonisation and expansion of github workflow
dcs4cop/xcube pull request #618
Opened 2022-02-24 08:56 UTC by AliceBalfanz

[Description of PR]
This PR only adjusts the github workflow. It harmonises the workflow based on https://github.com/dcs4cop/xcube-viewer/tree/master/.github/workflows and adds section to update k8s-configs for xcube-viewer app with the corresponding version in an automated manner. 
Checklist:

* ~~[ ] Add unit tests and/or doctests in docstrings~~
* ~~[ ] Add docstrings and API docs for any new/modified user-facing classes and functions~~
* ~~[ ] New/modified features documented in `docs/source/*`~~
* ~~[ ] Changes documented in `CHANGES.md`~~
* ~~[ ] AppVeyor CI passes~~
* ~~[ ] Test coverage remains or increases (target 100%)~~

Remember to close associated issues after merge!

2022-02-24 09:22 UTC, forman requested changes
If you want to abstract from actual image registry in use, you should not use "QUAY" here: 
```
          username: ${{ secrets.QUAY_REG_USERNAME }}
          password: ${{ secrets.QUAY_REG_PASSWORD }}
```

In the long-term: Actually this is not a general xcube workflow for the official xcube docker image, because this is an application of xcube for BC. It should actually go into another, BC-internal repo.

2022-02-24 09:22 UTC, forman commented on .github/workflows/xcube_workflow.yaml
> +  REG_NAME: quay.io
```suggestion
  IMG_REG_NAME: quay.io
```

2022-02-24 09:22 UTC, forman commented on .github/workflows/xcube_workflow.yaml
> +          password: ${{ secrets.QUAY_REG_PASSWORD }}
```suggestion
          registry: ${{ env.IMG_REG_NAME }}
          username: ${{ secrets.IMG_REG_USERNAME }}
          password: ${{ secrets.IMG_REG_PASSWORD }}
```

2022-02-24 09:22 UTC, forman commented on .github/workflows/xcube_workflow.yaml
> +          password: ${{ secrets.QUAY_REG_PASSWORD }}
```suggestion
          registry: ${{ env.IMG_REG_NAME }}
          username: ${{ secrets.IMG_REG_USERNAME }}
          password: ${{ secrets.IMG_REG_PASSWORD }}
```

2022-02-24 09:22 UTC, forman commented on .github/workflows/xcube_workflow.yaml
> +          HASH=$(skopeo inspect docker://${{ env.REG_NAME }}/${{ env.ORG_NAME }}/${{ env.APP_NAME }}:${{ steps.release.outputs.tag }} | jq '.Digest')
```suggestion
          HASH=$(skopeo inspect docker://${{ env.IMG_REG_NAME }}/${{ env.ORG_NAME }}/${{ env.APP_NAME }}:${{ steps.release.outputs.tag }} | jq '.Digest')
```

2022-02-24 12:41 UTC, TonioF reviewed
Seconding @forman's suggestions

2022-02-25 08:55 UTC, TonioF approved these changes

2022-02-28 08:03 UTC, forman approved these changes

2022-02-28 08:11 UTC, dzelge approved these changes

2022-03-01 09:04 UTC, merged