xcube serve does not provide datasets after service configuration changes
dcs4cop/xcube pull request #683
Opened 2022-05-10 09:22 UTC by TonioF

Solves #678. The changes in this PR ensure that there is always a DataStorePool in the service context, and that the dataset_configs correspond to its content. The DataStorePool is repopulated when it has been emptied, which usually happens after an external config change.

Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [x] Changes documented in `CHANGES.md`
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

2022-05-10 09:51 UTC, forman requested changes
Good! But please update according to my suggestions.

2022-05-10 09:51 UTC, forman commented on CHANGES.md
> +  configuration.
```suggestion
  configuration while the server is running.
```

2022-05-10 09:51 UTC, forman commented on CHANGES.md
> +  Previously, it was necessary to restart a service to load the changes. (#678)
```suggestion
  Previously, it was necessary to restart the server to load the changes. (#678)
```

2022-05-10 09:51 UTC, forman commented on xcube/webapi/context.py
> +                self._set_up_data_store_pool_and_dataset_configs()
Only lock, if needed. Double-check to be on the safe side (see https://en.wikipedia.org/wiki/Double-checked_locking).

```suggestion
        if self._dataset_configs is None:
            with self._lock:
                if self._dataset_configs is None:
                    self._set_up_data_store_pool_and_dataset_configs()
```

2022-05-10 09:51 UTC, forman commented on xcube/webapi/context.py
> +        with self._lock:
See above, use double-checked locking.

2022-05-11 14:36 UTC, AliceBalfanz approved these changes
From a pure usability aspect, this now works well. Tested locally.

2022-05-11 15:30 UTC, merged