Revision of xcube serve documentation
dcs4cop/xcube pull request #710
Opened 2022-07-08 14:40 UTC by AliceBalfanz

[Description of PR]
This PR changes documentation only. I have updated the description of server configuration file to also reflect DataStore configuration. 

Checklist:

* [ ] ~~Add unit tests and/or doctests in docstrings~~
* [ ] ~~Add docstrings and API docs for any new/modified user-facing classes and functions~~
* [x] New/modified features documented in `docs/source/*`
* [ ] ~~Changes documented in `CHANGES.md`~~
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

2022-07-11 11:21 UTC, TonioF commented
For review, see https://xcube.readthedocs.io/en/alicja-xxx-update-server-docs/cli/xcube_serve.html

2022-07-11 11:37 UTC, TonioF requested changes
See comments. Also, the references in section "Server Demo Configuration File for DataStores" do not work.

2022-07-11 11:37 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +The server configuration file consists of various parts, some of them are necessary others are optional.
```suggestion
The server configuration file consists of various parts, some of them are necessary, others are optional.
```

2022-07-11 11:37 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +:ref:`place-groups` and :ref:`styles`. Can be used in combination with :ref:`data-stores`.
```suggestion
This configuration file differs only in one part compared from :ref:`..config`. This part is :ref:`data-stores`.
The other main parts (:ref:`authentication`, :ref:`dataset-attribution`,
:ref:`place-groups`, and :ref:`styles`) can be used in combination with :ref:`data-stores`.
```

2022-07-11 11:37 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +as in :ref:`..config`.
Have a look at the layout on rtd

2022-07-11 11:37 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +*root* [mandatory] gives the common part of the path of the served datasets.
```suggestion
*root* [mandatory] states a common beginning part of the paths of the served datasets.
```

2022-07-11 11:37 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +serve the discovered datasets.
```suggestion
*max_depth* [optional] if wildcard is used in *Dataset Path* this indicates how far the server should step down in the directory structure to detect datasets that shall be served.
```

2022-07-11 11:37 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +configured, if the datasets are public-read, *anon* is set to "true", "false" indicates they are protected.
Add "Credentials" my be set with keywords 'key' and 'secret'."

2022-07-12 07:29 UTC, AliceBalfanz commented on docs/source/cli/xcube_serve.rst
> +                               entirely. Note, this will also suppress error and
This is the output of xcube serve --help, I will not change it here.

2022-07-12 07:29 UTC, AliceBalfanz commented on docs/source/cli/xcube_serve.rst
> +                               messages, i.e., -v refers to level INFO, -vv to
This is the output of xcube serve --help, I will not change it here.

2022-07-12 08:13 UTC, AliceBalfanz commented on docs/source/cli/xcube_serve.rst
> +    aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
They are :)

2022-07-25 14:21 UTC, TonioF requested changes
Almost none of the document-internal links work. Did you check them in the generated docs?

2022-07-25 14:21 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +Here the `demo configuration file`_ used in the `example`_ is explained in detail.
The example link does not work as you have two examples in this file. Can you rename them appropriately?

2022-07-25 14:21 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +`place groups`_ and `styles`_.
```suggestion
The configuration file consists of five main parts `authentication-optional`_, `dataset attribution-optional`_, `datasets-mandatory`_,
`place groups-optional`_ and `styles-optional`_.
```

2022-07-25 14:21 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +as well as an example of a `on-the-fly-generation-of-xcube-datasets`_.
Links are not working.

2022-07-25 14:21 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +the *PlaceGroupRef*. The configuration of *PlaceGroups* is described in section `place groups`_.
```suggestion
the *PlaceGroupRef*. The configuration of *PlaceGroups* is described in section `place-groups-optional`_.
```

2022-07-25 14:21 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +can only be used when providing `authentication`_. Datasets may be protected by
```suggestion
can only be used when providing `authentication-optional`_. Datasets may be protected by
```

2022-07-27 08:42 UTC, TonioF commented on docs/source/cli/xcube_serve.rst
> +This configuration file differs only in one part compared from `config`_. This part is `data stores`_.
```suggestion
This configuration file differs only in one part from :ref:`config`.
`the configuration above`_: `data stores`_.
```

Most of the configuration of locally stored datasets is equal to the configuration of
:ref:`remotely-stored-xcube-datasets`.
`remotely stored xcube datasets`_.

2022-07-27 08:45 UTC, TonioF approved these changes
One suggestion for improvement. However, I was not able to test whether this really works the way I want it, and I am okay if you don't accept it.

2022-07-27 09:16 UTC, merged