added example JNB for xcube cmems
dcs4cop/xcube pull request #738
Opened 2022-09-29 12:56 UTC by TejasMorbagal

[Description of PR]

Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [ ] Changes documented in `CHANGES.md`
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

2022-10-04 09:06 UTC, pont-us approved these changes

2022-10-04 13:12 UTC, TonioF requested changes
- Can you please run the notebooks so the cell outputs are updated?
- Please add a heading to the cmems notebook
- Have a look at my other comments

2022-10-04 13:12 UTC, TonioF commented on examples/notebooks/datastores/7_cmems_data_store.ipynb
> +    "Please checkout the general introduction to xcube data stores in the Jupyter Notebook Getting Started before jumping into this notebook :)\n",
Can you put this in italics, please?

2022-10-04 13:12 UTC, TonioF commented on examples/notebooks/datastores/7_cmems_data_store.ipynb
> +    "#### set `CMEMS_USER` and `CMEMS_PASSWORD` as environment variables"
Briefly state where you can get these.

2022-10-04 13:12 UTC, TonioF commented on examples/notebooks/datastores/7_cmems_data_store.ipynb
> +    "#### Get more info about a specific dataset. This includes a description of the possible open formats:"
```suggestion
    "#### Get more info about a specific dataset."
```
I realize you just copied this from other notebooks, but I don't know what is meant with "open formats" here.

2022-10-04 13:12 UTC, TonioF commented on examples/notebooks/datastores/7_cmems_data_store.ipynb
> +    "#### The dataset can be opened by giving variables_names, time_range and bbox as params. But note that none of them are mandatory"
```suggestion
    "#### The dataset can be opened by giving variables_names, time_range and bbox as params, but none of them are mandatory."
```

2022-10-05 09:23 UTC, forman requested changes
Please adhere _exactly_ to the style of the other Notebooks, e.g.,

It is not "XCUBE", but "xcube":

![image](https://user-images.githubusercontent.com/206773/194026788-e5784ea0-d9e6-4cc6-b559-7e7a8d410ba4.png)

Do not use bold header texts:

![image](https://user-images.githubusercontent.com/206773/194026939-af866d6d-a2fe-4870-b09f-03fe1a417ff4.png)

2022-10-05 09:39 UTC, TonioF commented
I'm getting confused. Why are there now changes to other modules?

2022-10-05 09:41 UTC, TejasMorbagal commented
> I'm getting confused. Why are there now changes to other modules?

Because I merged master into this branch, as Norman asked me.

2022-10-05 09:58 UTC, TonioF commented
> > I'm getting confused. Why are there now changes to other modules?
> 
> Because I merged master into this branch, as Norman asked me.

I see. It's weird github lists this as a changed file though.

2022-10-05 12:14 UTC, TonioF requested changes
Found one more little thing (see comment). Also, unfortunately I was unable to run the notebook because of a NotJSONError. Can you please have a look?

2022-10-05 12:14 UTC, TonioF commented on examples/notebooks/datastores/7_cmems_data_store.ipynb
> +    "Which parameters must be passsed or are available to open the dataset? "
```suggestion
    "Which parameters must be passed or are available to open the dataset? "
```

2022-10-05 12:45 UTC, TejasMorbagal commented
> Found one more little thing (see comment). Also, unfortunately I was unable to run the notebook because of a NotJSONError. Can you please have a look?

Notebook runs fine for me. Have you set cmems credentials as ENV VAR?

2022-10-05 13:48 UTC, TonioF commented
> > Found one more little thing (see comment). Also, unfortunately I was unable to run the notebook because of a NotJSONError. Can you please have a look?
> 
> Notebook runs fine for me. Have you set cmems credentials as ENV VAR?

I don't even get there. I receive this error message when I try to open the notebook: 
![image](https://user-images.githubusercontent.com/1598254/194076499-76d64178-002a-470a-91d6-695f9870e861.png)

2022-10-05 13:58 UTC, pont-us commented
> I don't even get there. I receive this error message when I try to open the notebook:

@TonioF Same here. Looks as though commit 241c196b5 broke it -- full stop character outside the string on line 154.

2022-10-05 14:15 UTC, TejasMorbagal commented
> > I don't even get there. I receive this error message when I try to open the notebook:
> 
> @TonioF Same here. Looks as though commit [241c196](https://github.com/dcs4cop/xcube/commit/241c196b5cfa37deb488b63683e2d990ea61d52f) broke it -- full stop character outside the string on line 158.

@pont-us @TonioF Yes, I reverted the commit. It works now. Kindly check and confirm

2022-10-06 08:48 UTC, AliceBalfanz commented on examples/notebooks/datastores/7_cmems_data_store.ipynb
> +    "set `CMEMS_USER` and `CMEMS_PASSWORD` as environment variables\n",
```suggestion
    "Set `CMEMS_USER` and `CMEMS_PASSWORD` as environment variables\n",
```

2022-10-06 08:51 UTC, AliceBalfanz commented on examples/notebooks/datastores/7_cmems_data_store.ipynb
> +    "The dataset can be opened by giving variables_names, time_range and bbox as params, but none of them are mandatory."
```suggestion
    "The dataset can be opened by giving `variables_names`, `time_range` and `bbox` as params, but none of them are mandatory."
```

2022-10-06 08:52 UTC, AliceBalfanz approved these changes
Minor change requests, but I don't insist :)

2022-10-06 10:41 UTC, forman approved these changes

2022-10-06 11:17 UTC, merged