Server NG to respect URL prefix
dcs4cop/xcube pull request #740
Opened 2022-10-04 18:24 UTC by forman

In this PR

* Server CLI respects the "--prefix" option.
* Server configuration respects the "url_prefix" parameter.

Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [ ] Changes documented in `CHANGES.md`
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

2022-10-05 06:03 UTC, AliceBalfanz commented
Tested locally and works well, but tests fail.

2022-10-05 06:04 UTC, AliceBalfanz requested changes
Once tests are fixed, I am happy :)

2022-10-05 06:44 UTC, forman commented
> Once tests are fixed, I am happy :)

Note this is still a draft, it was not ready for review...

2022-10-06 07:07 UTC, AliceBalfanz approved these changes

2022-10-06 08:29 UTC, merged