Programmatic xcube server
dcs4cop/xcube pull request #775
Opened 2022-12-30 07:33 UTC by forman

This PR is one step towards running xcube server/viewer from within Jupyter Notebooks.

This PR provides a new _interactive xcube server_ that can be launched programmatically from interactive shells such as Jupyter Notebooks. The interactive server can listen to any user-provided port. Users can add to the server, remove them, and list the currently served datasets. 

To test:

```python
from xcube.core.store import new_data_store
from xcube.webapi import InteractiveServer
store = new_data_store("file", root="examples/serve/demo")
ds = store.open_data("cube-1-250-250.levels")
iserver = InteractiveServer(port=8081)
iserver.add_dataset(ds)
```

```shell
$ curl http://localhost:8081/datasets
```

Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [ ] Changes documented in `CHANGES.md`
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

2023-01-31 15:22 UTC, thomasstorm approved these changes
Just a few minor suggestions, otherwise I'm happy!

2023-02-01 12:42 UTC, forman commented on CHANGES.md
> +  against the base directory of the xcube Server's configuration, i.e.
"using the```" ?

2023-02-01 14:07 UTC, AliceBalfanz requested changes
> added --open-viewer option that can open xcube Viewer after the server started

This only opens a new browser window of the default browser - but empty, not with the viewer url.

2023-02-01 14:23 UTC, AliceBalfanz commented on xcube/webapi/viewer/viewer.py
> +# Copyright (c) 2022 by the xcube team and contributors
```suggestion
# Copyright (c) 2023 by the xcube team and contributors
```

2023-02-01 14:25 UTC, AliceBalfanz commented on test/webapi/viewer/test_routes.py
> +# Copyright (c) 2022 by the xcube team and contributors
```suggestion
# Copyright (c) 2023 by the xcube team and contributors
```

2023-02-01 14:48 UTC, AliceBalfanz reviewed
When I use the parameter `--prefix xcube/api/latest`
the output of 
http://localhost:8080/xcube/api/latest/

looks as expected - but if I add the viewer parameter, the datasets are not shown:

![image](https://user-images.githubusercontent.com/23457217/216071047-bfdcccf7-ace8-43e5-a992-4291bdde8c30.png)

without passing a --prefix parameter this works fine:
![image](https://user-images.githubusercontent.com/23457217/216071396-ca4a94f1-14c4-497a-8fcd-90a82e5729dc.png)

2023-02-01 16:33 UTC, forman commented
> ... but if I add the viewer parameter, the datasets are not shown:

Unfortunately, this cannot easily be achieved because the viewer uses it's default server API configuration, which is at `http://localhost:8080`.

We need to make available an alternate viewer configuration via `http://localhost:8080/viewer/config/config.json` but this isn't yet implemented. After 0.13 release, let's create a feature request for that:

- xcube serve --config <PATH> ..., --> allow PATH to be an URI, e.g. pointing into S3 
- add server API endpoint /viewer/config/ to serve static viewer config resources
- allow xcube server config to also provide viewer config 


Then, we no longer need

- s3fuse deployments
- viewer deployments (because xcube server endpoint /viewer provides it already)

2023-02-02 08:28 UTC, AliceBalfanz approved these changes
Thanks for fixing the --open-viewer param

2023-02-02 14:02 UTC, merged