Support for Azure Blob filesystem update
dcs4cop/xcube pull request #798
Opened 2023-02-08 16:35 UTC by edd3x

[Description of PR]
Files  for Azure Blob Filesystem Data Store
The filesystem currently supported by xcube v0.13.0 include "file", "memory, and "AWS S3". This PR comprises updates that enable xcube data store instances to access files from the Microsoft Azure Blob storage filesystem using 
 'abfs' as store id, blob container as root, account_name and account_key or connection_string as store
 params. This is achieved via the <code>fsspec.AbstractFileSystem</code>  using the [fsspec adlfs](https://github.com/fsspec/adlfs) package.

Checklist:
* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [x] Changes documented in `CHANGES.md`
* [x] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

2023-02-09 13:28 UTC, forman commented
@edd3x thanks! Before we advance, could you please describe the PR (description is missing entirely) and tick the checklist items that are addressed by this PR. We will start reviewing only if checklist is complete.

2023-02-10 10:36 UTC, edd3x commented
@forman I have added the description to the PR. I ticked some items I have completed on the checklist. Please let me know if you require any other change

2023-02-13 19:51 UTC, forman commented
Hi @edd3x, your PR is not forgotten, but I only have limited time this week. Will take care asap.

2023-02-24 13:40 UTC, forman requested changes
Hey @edd3x, almost done :)

Please see my comments and suggestions. If you agree and fix stuff accordingly, I am happy to quickly approve & merge.

2023-02-24 13:40 UTC, forman commented on environment.yml
> +  - adlfs >=2023.1 # for azure blob filesystem
```suggestion
  - adlfs >=2023.1  # for azure blob filesystem
```

PEP8 wants 2 spaces between code and comment (we apply it for YAML as well)

2023-02-24 13:40 UTC, forman commented on test/test_AzureBlobFS.ipynb
> +{
Please adapt your Notebook to the conventions used in `example/notebooks/datastores` and move it there. Use the same naming convention.

2023-02-24 13:40 UTC, forman commented on CHANGES.md
> +  params.
See below: Please adapt your Notebook to the conventions used in `example/notebooks/datastores` and move it there. Use the same naming convention.

Mention its new location here.

2023-02-24 13:40 UTC, forman commented on xcube/core/store/fs/impl/fs.py
> +                **COMMON_STORAGE_OPTIONS_SCHEMA_PROPERTIES,
Please specify the Azure-specific store parameters here:

* `account_name`
* `account_key`
* `connection_string`

2023-02-24 13:43 UTC, forman commented on test/test_AzureBlobFS.ipynb
> +{
It should be named `8_azure_blob filesystem.ipynb`.

2023-03-02 17:11 UTC, forman approved these changes
Thanks, very good!

2023-03-03 13:38 UTC, merged

2023-03-16 10:17 UTC, edd3x commented
Hi @forman, I hope you are well; I have seen the new release of `xcube` and `xcube viewer`. I tried updating my server with the new version `xcube` and got an error when I ran the server. I noticed it was because of this line of code (`**COMMON_STORAGE_OPTIONS_SCHEMA_PROPERTIES,`) on line 172 of the `AzureFsAccessor()` class. 

Commenting or removing that line solved the problem.  Do I have to create a new pull request to fix this or it can be fixed from your end? 
Thanks

2023-03-16 11:01 UTC, forman commented
Hi @edd3x 

> Commenting or removing that line solved the problem. Do I have to create a new pull request to fix this

No, I'll have a look and try fixing this immediately. Will release a 1.0.2 asap.