Add a new_cluster function to xcube.util.dask
dcs4cop/xcube pull request #814
Opened 2023-02-16 11:31 UTC by pont-us

Fixes #813 .

Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [ ] Changes documented in `CHANGES.md`
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

2023-02-16 13:28 UTC, forman requested changes

2023-02-16 13:28 UTC, forman commented on environment.yml
> +  - coiled >=0.3.1
No. `coiled` is optional.

2023-02-16 13:28 UTC, forman commented on xcube/util/dask.py
> +        import coiled
Catch `ImportError` and re-raise with message saying that provide "coild" requires package `coiled` to be installed.

2023-02-16 13:28 UTC, forman commented on xcube/util/dask.py
> +        import coiled
```suggestion
            try:
                import coiled
            except ImportError as e:
                raise ImportError(f"provider 'coiled' requires package 'coiled' to be installed") from e            
```

2023-02-16 13:39 UTC, pont-us commented on environment.yml
> +  - coiled >=0.3.1
Fixed.

2023-02-16 16:44 UTC, forman commented
@pont-us can you please think of a way to unit-test the new function. Can we mock the `coiled` client interface?

2023-02-16 16:58 UTC, pont-us commented
> @pont-us can you please think of a way to unit-test the new function. Can we mock the `coiled` client interface?

Shouldn't be too hard, looking into it now.

2023-02-21 07:37 UTC, forman reviewed
Perfect, thanks :)

However, I still have a preference for `XCUBE_DASK_CLUSTER_...` instead of just `XCUBE_CLUSTER_...`, to separate from all other cluster-stuff that might exist in the xcube context, for example clustering classification algorithms or clusters of xcube servers..

2023-02-21 07:37 UTC, forman commented on xcube/util/dask.py
> +_CLUSTER_ACCOUNT_ENV_VAR_NAME = 'XCUBE_CLUSTER_ACCOUNT'
```suggestion
_CLUSTER_TAGS_ENV_VAR_NAME = 'XCUBE_DASK_CLUSTER_TAGS'
_CLUSTER_ACCOUNT_ENV_VAR_NAME = 'XCUBE_DASK_CLUSTER_ACCOUNT'
```

2023-02-21 07:37 UTC, forman commented on xcube/util/dask.py
> +    XCUBE_CLUSTER_TAGS in the format
```suggestion
    XCUBE_DASK_CLUSTER_TAGS in the format
```

2023-02-21 07:37 UTC, forman commented on xcube/util/dask.py
> +    variable ``XCUBE_CLUSTER_ACCOUNT``. If the ``account`` argument is
```suggestion
    variable ``XCUBE_DASK_CLUSTER_ACCOUNT``. If the ``account`` argument is
```

2023-02-21 08:47 UTC, merged